//-----------------------------------------------------------------------
// Semantic Directory — bundled dataset types + typed loader.
//
// Mirrors the exact shape emitted by scripts/build-demo-data.mjs. The JSON
// ships inside the app as the "brain" so the full experience works offline /
// outside the Fabric portal. The live model is layered on at runtime.
//-----------------------------------------------------------------------

import raw from "./catalog.dataset.json";

export interface BundleMeasure {
    name: string;
    table: string;
    folder: string | null;
    format: string | null;
    hidden: boolean;
    dax: string | null;
    description: string | null;
    sources: string[];
    stewardPending: boolean;
}

export interface BundleColumn {
    name: string;
    table: string;
    type: string | null;
    hidden: boolean;
    category: string | null;
    folder: string | null;
    description: string | null;
}

export interface BundleTable {
    name: string;
    storageMode: string | null;
    hidden: boolean;
    description: string | null;
    physicalSource: string | null;
    sourceSystem: string | null;
}

export interface BundleRelationship {
    fromTable: string;
    fromColumn: string;
    fromCardinality: string;
    toCardinality: string;
    toTable: string;
    toColumn: string;
    active: boolean;
    crossFilter: string;
}

export interface BundleSourceSystem {
    id: string;
    label: string;
    what: string;
    confidence: "confirmed" | "inferred";
}

export interface BundleFreshness {
    system: string;
    detail: string;
    latest: string;
    status: "fresh" | "stale";
    note?: string;
}

export interface BundleQaTieOut {
    area: string;
    system: string;
    passed: number;
    failed: number;
}

export interface BundleGlossary {
    term: string;
    meaning: string;
    confidence: "confirmed" | "inferred" | "standard";
    category: string;
    aliases: string[];
}

export interface BundleAdoption {
    _meta?: Record<string, unknown>;
    workspace_totals: { distinct_users: number; total_views: number };
    model_totals: { distinct_users: number; total_views: number; note?: string };
    top_reports: { report: string; views: number; users: number; kind?: string }[];
}

export interface CatalogDataset {
    generatedAt: string;
    source: {
        model: string;
        workspace: string;
        dataset: string;
        capturedUtc: string;
        note: string;
    };
    counts: Record<string, number>;
    measures: BundleMeasure[];
    columns: BundleColumn[];
    tables: BundleTable[];
    relationships: BundleRelationship[];
    sourceSystems: BundleSourceSystem[];
    freshness: BundleFreshness[];
    qaTieOut: BundleQaTieOut[];
    adoption: BundleAdoption;
    glossary: BundleGlossary[];
}

/** The bundled catalog brain, typed. */
export const dataset = validateDataset(raw);

/**
 * Fail fast instead of blind-casting. The bundle is generated by
 * scripts/build-demo-data.mjs, so a shape mismatch means the generator and
 * the app drifted — we want a loud, clear error at startup, not silently-
 * undefined fields surfacing as blank UI three screens deep. Cheap: runs once
 * at module load and only spot-checks structure, not every row.
 */
function validateDataset(input: unknown): CatalogDataset {
    const fail = (why: string): never => {
        throw new Error(`Bundled catalog is malformed: ${why}. Re-run scripts/build-demo-data.mjs.`);
    };
    if (typeof input !== "object" || input === null) fail("root is not an object");
    const d = input as Record<string, unknown>;

    if (typeof d.generatedAt !== "string") fail("missing generatedAt");
    if (typeof d.source !== "object" || d.source === null) fail("missing source");
    if (typeof d.counts !== "object" || d.counts === null) fail("missing counts");
    if (typeof d.adoption !== "object" || d.adoption === null) fail("missing adoption");

    const arrays = [
        "measures",
        "columns",
        "tables",
        "relationships",
        "sourceSystems",
        "freshness",
        "qaTieOut",
        "glossary",
    ] as const;
    for (const key of arrays) {
        if (!Array.isArray(d[key])) fail(`"${key}" is not an array`);
    }
    if ((d.measures as unknown[]).length === 0) fail("measures is empty");

    // Spot-check the first measure/column/table have their identifying fields —
    // catches a generator that changed field names without a schema bump.
    const m0 = (d.measures as unknown[])[0] as Record<string, unknown>;
    if (typeof m0?.name !== "string" || typeof m0?.table !== "string") {
        fail("measure rows are missing name/table");
    }

    return input as CatalogDataset;
}
